# Generated by Django 3.2.4 on 2021-06-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blogs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='blog-image/blog.png', upload_to='blog-image'),
        ),
    ]
