# Generated by Django 3.2.4 on 2021-06-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_blogs_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='likes',
        ),
    ]
